apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pod
  labels:
    app: backend-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
      - name: backend-container
        image: ksibbala04/backend:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: db-secret 
              key: uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secret 
              key: secret
        
