apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbpod
  labels:
    app: dbpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbpod
  template:
    metadata:
      labels:
        app: dbpod
    spec:
      containers:
      - name: db-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: db-secret  
              key: uri     