apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-pod
  labels:
    app: frontend-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - name: frontend-container
        image: ksibbala04/frontend:v1
        ports:
        - containerPort: 3000

        
