apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  #uri: mongodb+srv://mongouser:Arshad11@cluster0.ln64j.mongodb.net/?appName=Cluster0
  # value: 149BudgetManager165!
  uri: bW9uZ29kYitzcnY6Ly9tb25nb3VzZXI6QXJzaGFkMTFAY2x1c3RlcjAubG42NGoubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
  secret: MTQ5QnVkZ2V0TWFuYWdlcjE2NSE=

